In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

c:\Users\kumar\genai_env\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 100241.8828 - mae: 100241.8828 - val_loss: 98558.2656 - val_mae: 98558.2656
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100548.6875 - mae: 100548.6875 - val_loss: 97264.3281 - val_mae: 97264.3281
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97100.0859 - mae: 97100.0859 - val_loss: 93903.6953 - val_mae: 93903.6953
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 94342.4219 - mae: 94342.4219 - val_loss: 88180.5938 - val_mae: 88180.5938
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 87800.1797 - mae: 87800.1797 - val_loss: 80608.6406 - val_mae: 80608.6406
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 80511.8438 - mae: 80511.8438 - val_loss: 72277.8203 - val_mae: 72277.8203
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 71936.7969 - mae: 71936.7969 - val_loss: 64534.3203 - val_mae: 64534.3203
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 63393.6289 - mae: 63393.6289 - val_loss: 58394.0234 - val_mae: 58394.0234
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 57608.4414 - mae: 57608.4414 - val_loss: 54371.9414 - val_mae: 54371.9414
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 54168.6250 - mae: 54168.6250 - val_loss: 52168.9141 - val_mae: 52168.9141
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51525.1289 - mae: 51525.1289 - val_loss: 51302.9961 - val_mae: 51302.9961
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50629.4961 - mae: 50629.4961 - val_loss: 50986.0273 - val_mae: 50986.0273
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50752.0898 - mae: 50752.0898 - val_loss: 50876.8711 - val_mae: 50876.8711
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50244.0742 - mae: 50244.0742 - val_loss: 50803.8711 - val_mae: 50803.8711
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50858.6289 - mae: 50858.6289 - val_loss: 50747.2266 - val_mae: 50747.2266
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49771.9922 - mae: 49771.9922 - val_loss: 50699.4766 - val_mae: 50699.4766
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50406.8867 - mae: 50406.8867 - val_loss: 50655.7969 - val_mae: 50655.7969
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50251.7812 - mae: 50251.7812 - val_loss: 50618.0312 - val_mae: 50618.0312
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50599.6758 - mae: 50599.6758 - val_loss: 50586.9492 - val_mae: 50586.9492
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49860.5938 - mae: 49860.5938 - val_loss: 50553.0977 - val_mae: 50553.0977
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50605.1289 - mae: 50605.1289 - val_loss: 50523.8359 - val_mae: 50523.8359
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49754.2852 - mae: 49754.2852 - val_loss: 50499.0977 - val_mae: 50499.0977
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50044.3945 - mae: 50044.3945 - val_loss: 50472.4961 - val_mae: 50472.4961
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49902.9141 - mae: 49902.9141 - val_loss: 50453.0430 - val_mae: 50453.0430
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50610.3828 - mae: 50610.3828 - val_loss: 50429.6055 - val_mae: 50429.6055
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50045.6562 - mae: 50045.6562 - val_loss: 50413.7461 - val_mae: 50413.7461
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50111.9336 - mae: 50111.9336 - val_loss: 50396.3711 - val_mae: 50396.3711
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49719.3672 - mae: 49719.3672 - val_loss: 50385.9336 - val_mae: 50385.9336
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50004.4609 - mae: 50004.4609 - val_loss: 50371.3711 - val_mae: 50371.3711
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49775.0195 - mae: 49775.0195 - val_loss: 50359.2852 - val_mae: 50359.2852
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49780.8906 - mae: 49780.8906 - val_loss: 50343.3477 - val_mae: 50343.3477
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50427.9688 - mae: 50427.9688 - val_loss: 50330.2734 - val_mae: 50330.2734
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49406.8438 - mae: 49406.8438 - val_loss: 50329.0898 - val_mae: 50329.0898
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49968.4883 - mae: 49968.4883 - val_loss: 50323.0547 - val_mae: 50323.0547
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49264.7656 - mae: 49264.7656 - val_loss: 50318.6133 - val_mae: 50318.6133
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49225.7031 - mae: 49225.7031 - val_loss: 50311.2695 - val_mae: 50311.2695
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48961.3516 - mae: 48961.3516 - val_loss: 50299.8008 - val_mae: 50299.8008
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49327.6484 - mae: 49327.6484 - val_loss: 50293.2109 - val_mae: 50293.2109
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49703.3984 - mae: 49703.3984 - val_loss: 50290.6641 - val_mae: 50290.6641
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49466.8750 - mae: 49466.8750 - val_loss: 50291.5078 - val_mae: 50291.5078
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49826.9688 - mae: 49826.9688 - val_loss: 50286.0977 - val_mae: 50286.0977
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49986.2461 - mae: 49986.2461 - val_loss: 50275.7031 - val_mae: 50275.7031
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49955.1914 - mae: 49955.1914 - val_loss: 50274.8359 - val_mae: 50274.8359
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49376.4414 - mae: 49376.4414 - val_loss: 50271.5859 - val_mae: 50271.5859
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49603.6016 - mae: 49603.6016 - val_loss: 50270.3164 - val_mae: 50270.3164
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49169.4453 - mae: 49169.4453 - val_loss: 50268.6797 - val_mae: 50268.6797
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50045.5938 - mae: 50045.5938 - val_loss: 50263.5000 - val_mae: 50263.5000
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49831.6289 - mae: 49831.6289 - val_loss: 50268.4023 - val_mae: 50268.4023
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49334.7148 - mae: 49334.7148 - val_loss: 50277.8672 - val_mae: 50277.8672
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49470.3203 - mae: 49470.3203 - val_loss: 50278.0586 - val_mae: 50278.0586
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49431.1406 - mae: 49431.1406 - val_loss: 50287.1172 - val_mae: 50287.1172
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49722.5430 - mae: 49722.5430 - val_loss: 50277.9102 - val_mae: 50277.9102
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49251.6523 - mae: 49251.6523 - val_loss: 50288.8438 - val_mae: 50288.8438
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49303.7305 - mae: 49303.7305 - val_loss: 50287.2344 - val_mae: 50287.2344
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49667.9375 - mae: 49667.9375 - val_loss: 50284.0469 - val_mae: 50284.0469
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48918.3281 - mae: 48918.3281 - val_loss: 50282.9844 - val_mae: 50282.9844
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50018.9023 - mae: 50018.9023 - val_loss: 50290.4922 - val_mae: 50290.4922

In [17]:
%load_ext tensorboard

In [18]:
%tensorboard --logdir regressionlogs/fit

In [19]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51176.5078 - mae: 51176.5078
Test MAE : 50263.5

In [20]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.